#!/usr/bin/env bash
# A script that configures a new server and configure it to contain a custom header.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
ufw allow  'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
String="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/H-Asmaa permanent;"
sudo sed -i "s/server_name _;/$String/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "s/server_name _;/&\n\terror_page 404 \/custom_404.html;/" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
