#!/usr/bin/env bash
# script run Nginx and listen to port 80 of all the servers active IPv4 IPsz
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
