#!/usr/bin/env bash
# script run Nginx and listen to port 80 of all the servers active IPv4 IPsz
sudo apt-get install nginx -y
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop 
