#!/usr/bin/env bash
# A Bash script that stops 4-to_infinity_and_beyond process
kill -SIGTERM "$(pgrep -f 4-to_infinity_and_beyond)"
# kill -s SIGTERM $(pgrep -a bash | grep 4-to_infinity_and_beyond | cut -d ' ' -f 1)
# kill -n 15 $(pgrep -f 4-to_infinity_and_beyond)
