#!/usr/bin/env bash
# A Bash script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.
count=1
while [ $count -le 10 ]; do
	if test $count -eq 9
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
