#!/usr/bin/env bash
# Script to install the ufw firewall and set up rules on a server.

# Update package repository information
sudo apt-get update

# Install ufw
sudo apt-get install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

# Reload ufw to apply changes
sudo ufw reload
