#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
echo "8.8.8.8   localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
