#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts
echo '127.0.0.2 localhost' > ~/hosts
echo '8.8.8.8 facebook.com' >> ~/hosts
cat ~/hosts > /etc/hosts