#!/usr/bin/env bash

# Update the Nginx configuration to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default

# Update the Nginx configuration to run as the nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change ownership of the nginx directories to the nginx user
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /var/run/nginx

# Restart Nginx to apply changes
service nginx restart

